### ISSUE TITLE
punctuation.yaml 與 symbols.yaml 部分功能重複

### ISSUE THREAD

**Issue by sncix** [rime/rime-prelude#23]
punctuation.yaml 與 symbols.yaml  各包含一套全／半角標點，其中 symbols.yaml 經過多次更新後，已與 punctuation.yaml 稍有不同。目前，朙月拼音引用的是 symbols.yaml，而地球拼音則引用了 default.yaml，相當於間接引用了 punctuation.yaml。

提問：是否有必要維護這兩套標點，有沒有可能在儘量保持兼容性的前提下只保留其一？

---

p.s. 我在本地嘗試給 default.yaml 打了如下補丁，暫時沒有遇到什麼問題

```
patch:
  punctuator:
    full_shape:
      __include: symbols:/punctuator/full_shape
    half_shape:
      __include: symbols:/punctuator/half_shape
```

**Comment by lotem** [comment]
屬於歷史包袱。
這麼一改，肯定有用戶來報，某某符號原來能直接上屏，現在需要多選一次。

**Comment by sncix** [comment]
> 某某符號原來能直接上屏，現在需要多選一次。

檢查了一下，全角模式下這樣的符號有一個：`＝`；半角模式下有 `` ` ``、`@`、`#`、`=` 四個，但很多輸入方案（例如地球拼音）裏 `` ` `` 被用於反查，本來就不能直接上屏，這種情形下實際上受影響的只有 `@`、`#`、`=` 三個。

**Comment by lotem** [comment]
已有人用就得保留。
不能破壞用家的方案。
最多能夠把相同的代碼寫成引用的格式。
可是那樣代碼不如現在直觀~

**Comment by a84027129** [comment]
这个配置下半角字段定义的符号是中文的，正常不应该是英文标点么
half_shape:
    ',' : { commit: ， }
    '.' : { commit: 。 }

**Comment by a84027129** [comment]
symbols中这一段是引用自身么？不会引起循环？
patch:
  punctuator/import_preset: symbols
  recognizer/patterns/punct: '^/([0-9]0?|[A-Za-z]+)$'

**Comment by lotem** [comment]
> 这个配置下半角字段定义的符号是中文的，正常不应该是英文标点么

是中文句號和逗號。

`full_shape` 這個方案中的開關選項的功能是將所有ＡＳＣＩＩ字符以全角形式輸出，包括數字０～９，字母Ａ－Ｚａ－ｚ，空格　以及標點符號等等。與之相對「半角」模式是指 ASCII 字符默認輸出半角形式，但轉換之後的文字可能不屬於半角字符，如漢字。

該處配置中的 `half_shape` 是指通常「與半角文字搭配使用的中文標點」，`half_shape` 是指「與全角文字搭配使用的中文標點」。

`.` 鍵在中文輸入法中通常對應中文句號「。」，不是西文句號「.」也不是全角西文句號「．」。後者可以切換到西文模式再輸入，或者打開西文標點開關（`ascii_punct`）。

**Comment by lotem** [comment]
> symbols中这一段是引用自身么？不会引起循环？ patch: punctuator/import_preset: symbols recognizer/patterns/punct: '^/([0-9]0?|[A-Za-z]+)$'

不會。

這段是告訴用家如何打補丁使用這套標點，甚至可以直接引用：

```yaml
# foobar.custom.yaml
patch:
  __include: symbols:/patch
```

這段配置是純粹的 YAML 數據，沒有任何 [編譯指令](https://github.com/rime/home/wiki/Configuration#%E8%AA%9E%E6%B3%95)。
因此不會發生引用。
